CREATE TABLE 'user' (
    'id' INT(11) NOT NULL AUTO_INCREMENT,
    'name' VARCHAR(255) NOT NULL,
    'email' VARCHAR(255) NOT NULL UNIQUE,
    'password' VARCHAR(255) NOT NULL,
    'create_date' DATETIME NULL DEFAULT NULL,
    'modify_date' DATETIME NULL DEFAULT NULL,
    PRIMARY KEY ('id')
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
